### ISSUE TITLE
Looking Forward to the Open Sourcing of Your Project

### ISSUE THREAD

**Issue by iGuoYanjun** [jhaoshao/ChronoDepth#2]
Your research, especially the Temporal Inpaint Inference method described in your paper, is incredibly impressive.I am particularly interested in the details of how you implemented this method. 
I am eagerly looking forward to the open sourcing of your project. Even if you could release just the inference part of the code, it would be immensely helpful and greatly appreciated.
**Thank you again for your remarkable contributions. I hope to see the code released soon!**

**Comment by jiahao-shao1** [comment]
Hello, thank you for your interest in our work! We greatly appreciate it 🥰. We are excited to announce that we will be releasing our code soon, especially the inference part. Please keep an eye out for updates!
