### ISSUE TITLE
Export Frames

### ISSUE THREAD

**Issue by jtsanborn1** [jhaoshao/ChronoDepth#3]
Hi All, 

First of all, thank you for effort on this, I think this is the best depth estimation i've seen out there...

Just one quick question, how could we export png frames instead of a whole .mp4 video? also, is it possible to export only depth instead of colored? if so to both png and depth only, what is the command to do it or section to modify in the python script? 

Thanks for this!
TIA

**Comment by jiahao-shao1** [comment]
Thanks! You could refer to line 259-269 in file `run_infer.py` :)

**Comment by jtsanborn1** [comment]
> Thanks! You could refer to line 259-269 in file `run_infer.py` :)

I think this is for depth colored, but what about exporting frames instead of video file?

**Comment by jiahao-shao1** [comment]
<img width="839" alt="image" src="https://github.com/jhaoshao/ChronoDepth/assets/94811698/679ca9c5-3adc-4a6c-9026-dcc5874f92a9">
