### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by mohcenaouadj** [jhaoshao/ChronoDepth#6]
Hello, I read the paper, great work,

Can you provide us with the checkpoint file please in order to make the inference test possible ?

**Comment by jiahao-shao1** [comment]
The link is already included in the README file. https://huggingface.co/jhshao/ChronoDepth

**Comment by ray8828** [comment]
could you provide some instructions how to download the model checkpoint form HF? seems the command provided in the read me has a typo it's model_base not base_model and even after fix this bug we can't download the model, with error:
```sh
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/checkpoints/ChronoDepth
```

**Comment by jiahao-shao1** [comment]
Thanks for pointing out this bug. We've updated the command provided in the README. Try again now!
