### ISSUE TITLE
Type of depth your method predicts

### ISSUE THREAD

**Issue by haodong2000** [jhaoshao/ChronoDepth#8]
Dear authors,

There are 2 types of depth estimation I gauss your method aims to predict:

1. fully relative depth, predicts depth in 0~1.0
2. affine-invariant depth, predicts **absolute** depth, like Marigold in 2D depth estimation

Could you please tell me which type aligns with your method? 

Thanks so much!

Best,

**Comment by jiahao-shao1** [comment]
Thanks for noticing! Our method predicts affine-invariant depth like Marigold.
